In [1]:
import numpy as np

### Create an array from an iterable
Such as
- ```list```
- ```tuple```
- ```range``` iterator

Notice that not all iterables can be used to create a numpy array, such as ```set``` and ```dict```

In [1]:
# Creating a numpy array using a python List
import numpy 

li = [5.6,7.8,9.0]
np_array1 = numpy.array(li)
print(np_array1)
print(type(np_array1))

[5.6 7.8 9. ]
<class 'numpy.ndarray'>


In [2]:
# Creating a numpy array using a python tuple
import numpy 

li = (5.6,7.8,9.0)
np_array2 = numpy.array(li)
print(np_array2)
print(type(np_array2))

[5.6 7.8 9. ]
<class 'numpy.ndarray'>


In [3]:
# Creating a numpy array using a python Range 
import numpy 

np_array3 = numpy.array([range(1,21,2)])
print(np_array3)
print(type(np_array3))

[[ 1  3  5  7  9 11 13 15 17 19]]
<class 'numpy.ndarray'>


### Creating 1-D array

In [13]:
# Creating a numpy array using a python Range 
import numpy 

li = list(range(1,21,2))
np_array3 = numpy.array(li)
print(np_array3)
print(type(np_array3))
print(np_array3.ndim)
print(np_array3.shape)

[ 1  3  5  7  9 11 13 15 17 19]
<class 'numpy.ndarray'>
1
(10,)


### Creating 2-D array

In [14]:
np_array4 = numpy.array([[34,56],[56,78],[89,56]])
print(np_array4)
print(type(np_array4))
print(np_array4.ndim)
print(np_array4.shape)

[[34 56]
 [56 78]
 [89 56]]
<class 'numpy.ndarray'>
2
(3, 2)


### Creating 3-D array

In [38]:
np_array5 = numpy.array([[[45,67],[67,78],[67,89]],[[12,45],[45,34],[67,88]]])
print(np_array5)
print(type(np_array5))
print(np_array5.ndim)
print(np_array5.shape)
print("Total size used by array: ", (np_array5.itemsize)*len(np_array5.flatten()))

[[[45 67]
  [67 78]
  [67 89]]

 [[12 45]
  [45 34]
  [67 88]]]
<class 'numpy.ndarray'>
3
(2, 3, 2)
Total size used by array:  48


## Creating 4-D array

In [16]:
np_array6 = numpy.array([[[[45,67],[67,78],[67,89]],[[12,45],[45,34],[67,88]]]])
print(np_array6)
print(type(np_array6))
print(np_array6.ndim)
print(np_array6.shape)

[[[[45 67]
   [67 78]
   [67 89]]

  [[12 45]
   [45 34]
   [67 88]]]]
<class 'numpy.ndarray'>
4
(1, 2, 3, 2)


## Creating 10-D array

In [ ]:
np_array7 = numpy.array([[[[[[[[[[45,67],[67,78],[67,89]],[[12,45],[45,34],[67,88]]]]]]]]]])
print(np_array7)
print(type(np_array7))
print(np_array7.ndim)

In [20]:
# Creating a 3-D array using reshape method
np_array = numpy.arange(1,51)
np_array3d = np_array.reshape(2,5,5)
print(np_array3d)
print(np_array3d.ndim)
print(np_array3d.shape)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]]

 [[26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]
  [46 47 48 49 50]]]
3
(2, 5, 5)


In [21]:
# Creating a 3-D array using reshape method
np_array = numpy.arange(1,61)
np_array3d = np_array.reshape(2,5,-1)
print(np_array3d)
print(np_array3d.ndim)
print(np_array3d.shape)


[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]
  [13 14 15 16 17 18]
  [19 20 21 22 23 24]
  [25 26 27 28 29 30]]

 [[31 32 33 34 35 36]
  [37 38 39 40 41 42]
  [43 44 45 46 47 48]
  [49 50 51 52 53 54]
  [55 56 57 58 59 60]]]
3
(2, 5, 6)


In [22]:
# Creating a 10-D array using reshape method

np_array = numpy.arange(1,49)
np_array10d = np_array.reshape(1,1,1,1,1,1,2,2,3,4)
print(np_array10d)
print(np_array10d.ndim)
print(np_array10d.shape)

[[[[[[[[[[ 1  2  3  4]
         [ 5  6  7  8]
         [ 9 10 11 12]]

        [[13 14 15 16]
         [17 18 19 20]
         [21 22 23 24]]]


       [[[25 26 27 28]
         [29 30 31 32]
         [33 34 35 36]]

        [[37 38 39 40]
         [41 42 43 44]
         [45 46 47 48]]]]]]]]]]
10
(1, 1, 1, 1, 1, 1, 2, 2, 3, 4)


In [24]:
# Creating a 4-D array using reshape method

li = list(range(1,82))
ar = numpy.array(li)
arr4b = ar.reshape(3,3,3,-1) # last dimension(column) will be automatically calculated
arr4b

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]],


       [[[28, 29, 30],
         [31, 32, 33],
         [34, 35, 36]],

        [[37, 38, 39],
         [40, 41, 42],
         [43, 44, 45]],

        [[46, 47, 48],
         [49, 50, 51],
         [52, 53, 54]]],


       [[[55, 56, 57],
         [58, 59, 60],
         [61, 62, 63]],

        [[64, 65, 66],
         [67, 68, 69],
         [70, 71, 72]],

        [[73, 74, 75],
         [76, 77, 78],
         [79, 80, 81]]]])

### Create an array with specified data type

In [37]:
np_array5 = numpy.array([[[45,67],[67,78],[67,89]],[[12,45],[45,34],[67,88]]], dtype='int8')
print(np_array5)
print(type(np_array5))
print(np_array5.ndim)
print(np_array5.shape)
print(np_array5.dtype)
print("Total size used by array: ", (np_array5.itemsize)*len(np_array5.flatten()))

[[[45 67]
  [67 78]
  [67 89]]

 [[12 45]
  [45 34]
  [67 88]]]
<class 'numpy.ndarray'>
3
(2, 3, 2)
int8
Total size used by array:  12


In [39]:
np_array5 = numpy.array([[[45,67],[67,78],[67,89]],[[12,45],[45,34],[67,88]]], dtype='float16')
print(np_array5)
print(type(np_array5))
print(np_array5.ndim)
print(np_array5.shape)
print(np_array5.dtype)
print("Total size used by array: ", (np_array5.itemsize)*len(np_array5.flatten()))

[[[45. 67.]
  [67. 78.]
  [67. 89.]]

 [[12. 45.]
  [45. 34.]
  [67. 88.]]]
<class 'numpy.ndarray'>
3
(2, 3, 2)
float16
Total size used by array:  24


In [41]:
np_array5 = numpy.array([[[45,67],[67,78],[67,89]],[[12,45],[45,34],[67,88]]], dtype='complex64')
print(np_array5)
print(type(np_array5))
print(np_array5.ndim)
print(np_array5.shape)
print(np_array5.dtype)
print("Total size used by array: ", (np_array5.itemsize)*len(np_array5.flatten()))

[[[45.+0.j 67.+0.j]
  [67.+0.j 78.+0.j]
  [67.+0.j 89.+0.j]]

 [[12.+0.j 45.+0.j]
  [45.+0.j 34.+0.j]
  [67.+0.j 88.+0.j]]]
<class 'numpy.ndarray'>
3
(2, 3, 2)
complex64
Total size used by array:  96


In [ ]:
np_array5 = numpy.array([[[45,67],[67,78],[67,89]],[[12,45],[45,34],[67,88]]], dtype='int8')
print(np_array5)
print(type(np_array5))
print(np_array5.ndim)
print(np_array5.shape)
print(np_array5.dtype)
print("Total size used by array: ", (np_array5.itemsize)*len(np_array5.flatten()))

In [47]:
np_array5 = numpy.array([[[45,67],[67,78],[67,89]],[[12,45],[45,34],[67,88]]], dtype='U1')
print(np_array5)
print(type(np_array5))
print(np_array5.ndim)
print(np_array5.shape)
print(np_array5.dtype)
print("Total size used by array: ", (np_array5.itemsize)*len(np_array5.flatten()))

[[['4' '6']
  ['6' '7']
  ['6' '8']]

 [['1' '4']
  ['4' '3']
  ['6' '8']]]
<class 'numpy.ndarray'>
3
(2, 3, 2)
<U1
Total size used by array:  48


### Create an aray within specified range
```np.arange()``` method can be used to replace ```np.array(range())``` method

In [49]:
# np.arange(start, stop, step)

arr11 = numpy.arange(4,11,2)
arr11

array([ 4,  6,  8, 10])

### Create an array of evenly spaced numbers within specified range
```np.linspace(start, stop, num_of_elements, endpoint=True, retstep=False)``` has 5 parameters:
- ```start```: start number (inclusive)
- ```stop```: end number (inclusive unless ```endpoint``` set to ```False```)
- ```num_of_elements```: number of elements contained in the array
- ```endpoint```: boolean value representing whether the ```stop``` number is inclusive or not
- ```retstep```: boolean value representing whether to return the step size

In [70]:
import random

random.seed(12345)
for i in range(10):
    print(random.randint(1,100))

54
94
2
39
48
25
35
73
56
21


### Create an array of random values of given shape
```numpy.random.rand()``` method returns values in the range [0,1)

In [74]:
arr = numpy.random.rand(2,3, 3)
print(arr)

[[[0.56795844 0.24541541 0.67961135]
  [0.99360759 0.96282753 0.48370119]
  [0.60901648 0.75342724 0.963311  ]]

 [[0.68361445 0.28228904 0.76859346]
  [0.67231749 0.27235024 0.4465061 ]
  [0.55390656 0.66155582 0.26193006]]]


In [75]:
arr111 = numpy.random.randint((1,100),3, 3)
print(arr111)

ValueError: low >= high

### Create an array of zeros of given shape 
- ```np.zeros()```: create array of all zeros in given shape
- ```np.zeros_like()```: create array of all zeros with the same shape and data type as the given input array

In [76]:
# Array of complex zero


### Create an array of ones of given shape 
- ```np.ones()```: create array of all ones in given shape
- ```np.ones_like()```: create array of all ones with the same shape and data type as the given input array

### Create an empty array of given shape 
- ```np.empty()```: create array of empty values in given shape
- ```np.empty_like()```: create array of empty values with the same shape and data type as the given input array

Notice that the initial values are not necessarily set to zeroes.

They are just some garbage values in random memory addresses.

### Create an array of constant values of given shape  
- ```np.full()```: create array of constant values in given shape
- ```np.full_like()```: create array of constant values with the same shape and data type as the given input array

### Create an array in a repetitive manner
- ```np.repeat(iterable, reps, axis=None)```: repeat each element by n times
    - ```iterable```: input array
    - ```reps```: number of repetitions
    - ```axis```: which axis to repeat along, default is ```None``` which will flatten the input array and then repeat
- ```np.tile()```: repeat the whole array by n times
    - ```iterable```: input array
    - ```reps```: number of repetitions, it can be a tuple to represent repetitions along x-axis and y-axis

In [86]:
# No axis specified, then flatten the input array first and repeat


In [87]:
# An example of repeating along x-axis


In [88]:
# An example of repeating along y-axis


In [89]:
# Repeat the whole array by a specified number of times


### Create an identity matrix of given size
- ```np.eye(size, k=0)```: create an identity matrix of given size
    - ```size```: the size of the identity matrix
    - ```k```: the diagonal offset
- ```np.identity()```: same as ```np.eye()``` but does not carry parameters

In [23]:
# An example of diagonal offset
identity_matrix = np.eye(5, k=-1)
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [24]:
identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Create an array with given values on the diagonal

In [25]:
arr = np.random.rand(5,5)
print(arr)
# Extract values on the diagonal
print('Values on the diagonal: ' + str(np.diag(arr)))

[[0.04481892 0.32920508 0.09746329 0.88717729 0.73704537]
 [0.99842459 0.3842842  0.55263992 0.76554596 0.55017239]
 [0.48540154 0.85297201 0.82429168 0.27125055 0.79634355]
 [0.41327049 0.68932437 0.10586385 0.48118436 0.476337  ]
 [0.05556156 0.27141898 0.11705936 0.83691925 0.49439961]]
Values on the diagonal: [0.04481892 0.3842842  0.82429168 0.48118436 0.49439961]


In [26]:
# Not necessarily to be a square matrix
arr = np.random.rand(10,3)
print(arr)
# Extract values on the diagonal
print('Values on the diagonal: ' + str(np.diag(arr)))

[[0.44008485 0.19254758 0.65707551]
 [0.06838026 0.43745833 0.22630033]
 [0.86801201 0.65430091 0.93617918]
 [0.72927673 0.61550749 0.87328398]
 [0.11083138 0.15582005 0.54587358]
 [0.80298985 0.89705779 0.18045105]
 [0.93153603 0.84343715 0.39326583]
 [0.29509183 0.49859358 0.32320668]
 [0.13389313 0.6620257  0.50146751]
 [0.69110925 0.97077549 0.11649333]]
Values on the diagonal: [0.44008485 0.43745833 0.93617918]


In [90]:
# Create a matrix given values on the diagonal
# All non-diagonal values set to zeros
